### ISSUE TITLE
rdflib import error

### ISSUE THREAD

**Issue by AlasdairGray** [schemaorg/sdopythonapp#10]
Trying to get the new build system running on my local machine. I've checkout a clean version of the latest schemaorg master. I get the following error when I run `./runpythonapp.sh` with the default options

```
INFO     2020-05-21 08:54:47,577 devappserver2.py:278] Skipping SDK update check.
WARNING  2020-05-21 08:54:47,679 simple_search_stub.py:1196] Could not read search indexes from /var/folders/wv/ztzfmc6s70b54bs4t226nl480000gn/T/appengine.None.ajg33/search_indexes
INFO     2020-05-21 08:54:47,683 api_server.py:275] Starting API server at: http://localhost:50891
INFO     2020-05-21 08:54:47,705 dispatcher.py:256] Starting module "default" running at: http://localhost:8080
INFO     2020-05-21 08:54:47,709 admin_server.py:150] Starting admin server at: http://localhost:8000
INFO     2020-05-21 08:54:49,903 instance.py:294] Instance PID: 23087
ERROR    2020-05-21 08:54:50,379 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/ajg33/bin/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/ajg33/bin/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/ajg33/bin/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/ajg33/tmp/schemaorg/sdopythonapp/sdoapp.py", line 19, in <module>
    import rdflib
  File "/Users/ajg33/tmp/schemaorg/sdopythonapp/lib/rdflib/__init__.py", line 117, in <module>
    import six
ImportError: No module named six
INFO     2020-05-21 08:54:50,387 module.py:861] default: "GET /_ah/warmup HTTP/1.1" 500 -
```
The homepage displays and some of the documentation pages but none of the schemas.

**Comment by AlasdairGray** [comment]
I'm on app engine version 245.0.0 in case that is relevant. I just tried upgrading to 293.0.0 but started causing errors saying the python2 could not be found.

**Comment by AlasdairGray** [comment]
It seems that the problem relates to the version of gcloud I had. 

Now that I've added in a link for `python2` and updated to the latest gcloud the system works as expected.
```
ln -s python /usr/bin/python2.7 /usr/local/bin/python2
```
